project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('companys.urls')),
    path('vagas/', include('vacancies.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vacancies/urls.py
from django.urls import path

from vacancies import views

urlpatterns = [
    path('nova-vaga/', views.new_vacancy, name="new_vacancy" ),
    path('vaga/<int:id>', views.show_vacancy, name="show_vacancy"),
    path('nova-tarefa/<int:id_vacancy>', views.new_task, name="new_task"),
    path('realizar_tarefa/<int:id>', views.finish_task, name='finish_task'),
    path('envia-email/<int:id_vacancy>', views.send_email, name="send_email")
]

vacancies/models.py
from django.db import models
from django.utils.safestring import mark_safe

from companys.models import Vacancy


class Task(models.Model):
    choices_priority = (
        ('B', 'Baixa'),
        ('A', 'Alta'),
        ('U', 'Urgente')
    )
    vacancy = models.ForeignKey(Vacancy, on_delete=models.CASCADE)
    title = models.CharField(max_length=30)
    priority = models.CharField(max_length=1, choices=choices_priority)
    date = models.DateField()
    concluded = models.BooleanField(default=False)


    def icon(self):
        if self.priority == "U":
            css_class = 'prioridade-vermelho'
        elif self.priority == "A":
            css_class = 'prioridade-amarelo'
        elif self.priority == "B":
            css_class = 'prioridade-verde'

        icon = f'''<svg  class="{css_class}" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle-fill" viewBox="0 0 16 16">
                                    <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                    </svg>'''

        return mark_safe(icon)

    def __str__(self):
        return self.title

class Emails(models.Model):
    vacancy = models.ForeignKey(Vacancy, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    main_text = models.TextField()
    sent = models.BooleanField()

    def __str__(self):
        return self.title

vacancies/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.messages import constants
from django.core.mail import EmailMultiAlternatives
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.template.loader import render_to_string
from django.utils.html import strip_tags

from companys.models import Vacancy
from vacancies.models import Emails, Task


def new_vacancy(request):
    if request.method == "POST":
        title = request.POST.get('title')
        email = request.POST.get('email')
        technologies_mastered = request.POST.get('technologies_mastered')
        technologies_to_study = request.POST.get('technologies_to_study')
        experience = request.POST.get('experience')
        final_date = request.POST.get('final_date')
        company = request.POST.get('company')
        status = request.POST.get('status')


        vacancy = Vacancy(
                    title=title,
                    email=email,
                    lvl_experience=experience,
                    final_date=final_date,
                    company_id=company,
                    status=status,
        )


        vacancy.save() 

        vacancy.technologies_to_study.add(*technologies_to_study)
        vacancy.technologies_matereds.add(*technologies_mastered)

        vacancy.save()

        messages.add_message(request, constants.SUCCESS, 'Vaga criada com sucesso.')
        return redirect(f'/home/empresa/{company}')
    elif request.method == "GET":
        raise Http404()

def show_vacancy(request, id):
    vacancy = get_object_or_404(Vacancy, id=id)
    tasks = Task.objects.filter(vacancy=vacancy).filter(concluded=False)
    emails = Emails.objects.filter(vacancy=vacancy)
    
    context = {
        'vacancy': vacancy,
        'tasks': tasks,
        'email': emails
    }

    return render(request, 'vacancy_details.html', context)

def new_task(request, id_vacancy):
    title = request.POST.get('title')
    priority = request.POST.get('priority')
    date = request.POST.get('date')
    
    task = Task(vacancy_id=id_vacancy,
                    title=title,
                    priority=priority,
                    date=date)
    task.save()
    messages.add_message(request, constants.SUCCESS, 'Tarefa criada com sucesso')
   
    return redirect(f'/vagas/vaga/{id_vacancy}')

def finish_task(request, id):
    task_list = Task.objects.filter(id=id).filter(concluded=False)

    if not task_list.exists():
        messages.add_message(request, constants.ERROR, 'Erro interno do sistema!')
        return redirect(f'/home/empresas/')

    task = task_list.first()
    task.concluded = True
    task.save()    
    messages.add_message(request, constants.SUCCESS, 'Tarefa realizada com sucesso, parabéns!')
    return redirect(f'/vagas/vaga/{task.vacancy.id}')

def send_email(request, vacancy_id):
    vacancy = Vacancy.objects.get(id=vacancy_id)
    title = request.POST.get('title')
    main_text = request.POST.get('main_text')

    html_content = render_to_string('emails/template_email.html', {'main_text': main_text})
    text_content = strip_tags(html_content)
    email = EmailMultiAlternatives(title, text_content, settings.EMAIL_HOST_USER, [vacancy.email,])
    email.attach_alternative(html_content, "text/html")

    if email.send():  
        email_to_save = Emails(
            vacancy=vacancy,
            title=title,
            main_text=main_text,
            sent=True
        )

        email_to_save.save()

        messages.add_message(request, constants.SUCCESS, 'Email enviado com sucesso.')
        return redirect(f'/vagas/vaga/{vacancy_id}')
    else:
        email_to_save = Emails(
            vacancy=vacancy,
            title=title,
            main_text=main_text,
            sent=False
        )

        email_to_save.save()

        messages.add_message(request, constants.ERROR, 'Erro interno do sistema!')
        return redirect(f'/vagas/vaga/{vacancy_id}')

vacancies/templates/vacancy_details.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'vacancy/css/vacancy_details.css' %}"> 
{% endblock %}

{% block content %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
            <br>
                <section class="alert {{message.tags}}">
                    {{message}}
                </section>
            {% endfor %}
        {% endif %}
        <br>
        <h3 class="titulo">{{vacancy.title}}</h3>
        <p class="titulo2">{{vacancy.company}}</p>
        <p>Progresso atual</p>
        
        <div style="width: 40%" class="progress">
            <div class="progress-bar progress-bar-striped bg-success" role="progressbar" style="width: {{vacancy.progress}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
    </div>

    <div class="bg2">
        <div class="container">
            <div class="row">
                <div class="col-md">
                    <p class="titulo2">Crie uma tarefa</p>
                    <p>Lembre-se de realizar todas suas tarefas com antecedência</p>


                    <form action="{% url 'new_task' vacancy.id %}" method="POST">{% csrf_token %}
                        <label>Título:</label>
                        <input name="title" type="text" class="form-control input-tarefa" placeholder="Digite o título da tarefa..."> 
                        <br>
                        <label>Prioridade:</label>
                        <select name="priority" class="form-select input-tarefa">
                            <option value="U">Urgente</option>
                            <option value="A">Alta</option>
                            <option value="B">Baixa</option>
                        </select>
                        <br>
                        <label>Data:</label>
                        <input name="date" type="date" class="form-control input-tarefa" placeholder=""> 
                        <br>
                        <input type="submit" value="Nova tarefa" class="btn btn-orange">

                    </form>

                </div>

                <div class="col-md">
                    {% for task in tasks %}
                        <div class="li-tarefa">
                            <label class="li-tarefa-item">{{task.title}}</label>
                            <label class="prioridade-bloco li-tarefa-item">
                                {{task.icon}}
                                {{task.get_priority_display}}
                            </label>
                            <label class="prioridade-bloco li-tarefa-item">
                                {{task.date|date:'d/m/Y'}}
                            </label>
                            <label class="prioridade-bloco li-tarefa-item">
                                <a href="{% url 'finish_task' task.id %}" class="btn btn-success">Finalizado</a>
                            </label>
                    
                        </div>
                {% endfor %}
                </div>

            </div>
        </div>

    </div>

    <div class="container bg3">
        <div class="row">

            <div class="col-md">
                <p class="titulo2">Enviar E-mail</p>
                <p>Envie e-mails para essa vaga por aqui.</p>
            </div>

            <div class="col-md">
                <form action="{% url 'send_email' vacancy.id%}" method="POST">
                    <label>Assunto:</label>
                    <input name="title" type="text" class="form-control" placeholder="assunto">
                    <br>
                    <label>Corpo do email:</label>
                    <textarea name="main-text" class="form-control"></textarea>
                    <br>
                    <input type="submit" class="btn btn-orange" value="Enviar">
                </form>
            </div>
        </div>

    </div>


    <div class="bg2">
        <div class="container">
            <div class="row"> 
                <h3 class="titulo">Histórico de e-mails</h3>
                
                {% for email in emails%}
                <div class="col-md">
            
                    <div class="box-email">
                        <div class="header-email">
                            {{email.title}}
                        </div>
            
                        <div class="body-email">
                            {{email.main_text}}
                        </div>
                        
                    </div>
            
                </div>
            {% endfor %}
                
                
                  
            </div> 
            
                    
        </div>
    </div>

    <div class="container bg3">
        <div class="row">
            <div class="col-md">
                <p class="titulo2">Tecnologias que domino</p>
                {% for tech in vacancy.technologies_matereds.all %}
                <div class="li-tech">
                    {{tech}}
                    <svg class="arrow-right" xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-right" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M1 8a.5.5 0 0 1 .5-.5h11.793l-3.147-3.146a.5.5 0 0 1 .708-.708l4 4a.5.5 0 0 1 0 .708l-4 4a.5.5 0 0 1-.708-.708L13.293 8.5H1.5A.5.5 0 0 1 1 8z"/>
                    </svg>
                </div>
                {% endfor %}


            </div>

            <div class="col-md">
                <p class="titulo2">Preciso estudar</p>
                {% for tech in vacancy.technologies_to_study.all %}
                
                <div class="li-tech">
                    <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    {{tech}}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}