companys/urls.py
from django.urls import path

from companys import views

urlpatterns = [
    path ('nova_empresa/', views.new_companys, name="new_company"),
    path('empresas/', views.show_companys, name="show_companys"),
    path('excluir_empresa/<int:id>', views.delete_companys, name="delete_company"),
    path('empresa/<int:id>', views.company_details, name="company_details")
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('companys.urls')),
    path('vagas/', include('vacancies.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

companys/models.py
from django.db import models


class Technology(models.Model):
    technology = models.CharField(max_length=30, verbose_name="tecnologia")

    def __str__(self):
        return self.technology

class Company(models.Model):
    choices_category = (
        ('M', 'Marketing'),
        ('N', 'Nutrição'),
        ('D', 'Design'),
        ('T', 'Tecnologia')
    )
    logo  = models.ImageField(upload_to="logo_company")
    name  = models.CharField(max_length=30, verbose_name="nome")
    email = models.EmailField(null=True)
    city = models.CharField(max_length=30, verbose_name="cidade")
    technology = models.ManyToManyField(Technology, verbose_name="tecnologias")
    address = models.CharField(max_length=60, verbose_name="endereço")
    market_category = models.CharField(max_length=3, choices=choices_category, verbose_name="nicho_de_mercado")
    company_characteristics = models.TextField(verbose_name="caracteristicas_empresa")

    def __str__(self) -> str:
        return self.name

    def number_job_vacancies(self):
        return Vacancy.objects.filter(company__id=self.id).count()
    



class Vacancy(models.Model):
    choices_experience = (
        ('J', 'Júnior'),
        ('P', 'Pleno'),
        ('S', 'Sênior')
    )

    choices_status = (
        ('I', 'Interesse'),
        ('C', 'Currículo enviado'),
        ('E', 'Entrevista'),
        ('D', 'Desafio técnico'),
        ('F', 'Finalizado')
    )
    
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING, verbose_name="empresa")
    title = models.CharField(max_length=30, verbose_name="titulo")
    email = models.EmailField(null=True)
    lvl_experience = models.CharField(max_length=2, choices=choices_experience, verbose_name="nivel de experiencia")
    final_date = models.DateField(verbose_name="data final")
    status = models.CharField(max_length=30, choices=choices_status)
    technologies_to_study = models.ManyToManyField(Technology, related_name='estudar', verbose_name="Tecnologias para estudar")
    technologies_matereds = models.ManyToManyField(Technology, verbose_name="Tecnologias dominadas")


    def progress(self):
        x = [((i+1)*20,j[0]) for i, j in enumerate(self.choices_status)]
        x = list(filter(lambda x: x[1] == self.status, x))[0][0]
        return x

    def __str__(self):
        return self.title

companys/views.py
from django.contrib import messages
from django.contrib.messages import constants
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse

from companys.models import Company, Technology, Vacancy


def new_companys(request):

    if request.method == "GET":
        techs = Technology.objects.all()
        
        context = {
            "techs": techs
        }

        return render(request, 'new_company.html', context)
        
    elif request.method == "POST":
        name  = request.POST.get('name')
        email = request.POST.get('email')
        city  = request.POST.get('city')
        address  = request.POST.get('address')
        category = request.POST.get('category')
        characteristics = request.POST.get('characteristics')
        technologies = request.POST.getlist('technologies')
        logo = request.FILES.get('logo')

        if (len(name.strip()) == 0 or len(email.strip()) == 0 or len(city.strip()) == 0 or len(address.strip()) == 0 or len(category.strip()) == 0 or len(characteristics.strip()) == 0 or (not logo)): 
            messages.add_message(request, constants.ERROR, 'Preencha todos os campos')
            return redirect(reverse('new_company'))

        if logo.size > 100_000_000:
            messages.add_message(request, constants.ERROR, 'A logo da empresa deve ter menos de 10MB')
            return redirect(reverse('new_company'))

        if category not in [i[0] for i in Company.choices_category]:
            messages.add_message(request, constants.ERROR, 'Nicho de mercado inválido')
            return redirect(reverse('new_company'))

        companys = Company(logo=logo,
                        name=name,
                        email=email,
                        city=city,
                        address=address,
                        market_category=category,
                        company_characteristics=characteristics
                    )

        companys.save()
        companys.technology.add(*technologies)
        companys.save()
        messages.add_message(request, constants.SUCCESS, 'Empresa cadastrada com sucesso')
        return redirect(reverse('show_companys'))

def show_companys(request):
    companys  = Company.objects.all()
    technologies = Technology.objects.all()

    tech_filter = request.GET.get('technologies')
    name_filter = request.GET.get('name')

    if tech_filter:
        if tech_filter == "Todas":
            companys = companys.all()
        else:
            companys = companys.filter(technology = tech_filter)

    if name_filter:
       companys = companys.filter(name__icontains = name_filter)

    context = {
        "companys":  companys,
        "technologies": technologies
    }

    return render(request, 'companys.html', context)

def delete_companys(request, id):
    company = Company.objects.get(id=id)
    company.delete()

    messages.add_message(request, constants.SUCCESS, 'Empresa excluída com sucesso')
    
    return redirect(reverse('show_companys'))

def company_details(request, id):
    company = get_object_or_404(Company, id=id)

    companys =  Company.objects.all()
    technologies = Technology.objects.all()
    vacancies = Vacancy.objects.filter(company_id=id)

    context = {
        'company': company,
        'companys': companys,
        'technologies': technologies,
        'vacancies': vacancies
    }

    return render(request, 'company_details.html', context)

companys/templates/company_details.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'company/css/company_details.css' %}" rel="stylesheet">
{% endblock%}


{% block content %}

    
    <br>
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <br>
                <section class="alert {{message.tags}}">
                    {{message}}
                </section>
            {% endfor %}
        {% endif %}    
        <div class="row">
            <div class="col-md-3">
                <img width="100%" src="{{company.logo.url}}">
            </div>

            <div class="col-md">
                <h1 class="titulo">{{company.name}}</h1>
                <p class="paragrafo">{{company.address}}</p>
            </div>



        </div>
        <br>
        <div class="row">
            <div class="col-md-6">
                <label>Nicho de mercado:</label>
                <input disabled type="text" class="form-control" value="{{ company.get_market_category_display }}">
            </div>

            <div class="col-md-3">
                <label>Tecnologias usadas:</label>
                <select class="form-select">
                    {% for tech in company.technology.all %}
                        <option>{{tech}}</option>
                    {% endfor %}   

                </select>
                
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-7">
                <label>Características da empresa:</label>
                <textarea disabled class="form-control">{{company.company_characteristics}}</textarea>
            </div>

            <div class="col-md-3">
                
                
            </div>
        </div>

        <hr>

        <a data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-lg btn-orange">Nova vaga</a>

        <div class="row">
            {% for vacancy in vacancies %}
            <div class="col-md">
        
            <div class="box-vagas">
                <div class="header-vagas">
                    <a class="title-link-vacancy" href="{% url 'show_vacancy' vacancy.id %}">{{vacancy.title}}</a>
                </div>
        
                <div class="body-vagas">
                    <div class="row">
                        <div class="col-md">
                            <label class="text-1">Nível:</label>
                            <br>        
                            <label class="text-1 text-1-orange">{{vacancy.get_lvl_experience_display}}</label>                           
                        </div>
        
                        <div class="col-md">
                            <label class="text-1">Status <img src="{% static 'company/img/green-flag.svg' %}"></label>
                            <br>        
                            <label class="text-1 text-1-orange">{{vacancy.get_status_display}}</label>                           
                        </div>
        
                    </div>
                </div>
                
            </div>
                
            </div>
        {% endfor %}
        </div>

        <div class="modal fade modal-lg" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                <div class="modal-header">
                    <h5 style="font-size: 30px" class="modal-title titulo" id="exampleModalLabel">Nova vaga</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form action="{% url 'new_vacancy' %}" method="POST">{% csrf_token %}
                        <div class="row">
                            <div class="col-md">
                                <label>Título:</label>
                                <input type="text" name="title" class="form-control" placeholder="Digite o título da vaga...">
                            </div>
    
                            <div class="col-md">
                                <label>Email:</label>
                                <input type="email" name="email" class="form-control" placeholder="email@email.com.br">
                            </div>
                            
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <label>Tecnologias que já domino:</label>
                                <select name="technologies_mastered" class="form-select" multiple>
                                    {% for tech in technologies %}
                                        <option value="{{tech.id}}">{{tech}}</option>
                                    {% endfor %}
    
                                </select>
                            </div>
    
                            <div class="col-md">
                                <label>Tecnologias que não domino:</label>
                                <select name="technologies_to_study" class="form-select" multiple>
                                    {% for tech in technologies %}
                                        <option value="{{tech.id}}">{{tech}}</option>
                                    {% endfor %}
    
                                </select>
                            </div>
                            
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <label>Nível de experiência:</label>
                                <select name="experience" class="form-select">
                                    <option value="J">Júnior</option>
                                    <option value="P">Pleno</option>
                                    <option value="S">Sênior</option>
                                </select>
                            </div>
    
                            <div class="col-md">
                                <label>Data final:</label>
                                <input type="date" class="form-control" name="final_date"> 
                                
                            </div>
                            
                        </div>
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <label>Empresa:</label>
                                <select name="company" class="form-select">
                                    {% for company in companys %}
                                        <option value="{{company.id}}">{{ company.name }}</option>
                                    {% endfor %}                                                                                         
                                </select>
                            </div>
           
                        </div>
    
                        <br>
                        <div class="row">
                            <div class="col-md">
                                <label>Status:</label>
                                <select name="status" class="form-select">     
                                    <option value="I">Interesse</option>
                                    <option value="C">Currículo enviado</option>    
                                    <option value="E">Entrevista</option>    
                                    <option value="D">Desafio técnico</option>    
                                    <option value="F">Finalizado</option>          
                                </select>
                            </div>
           
                        </div>
                        <br>
                        <input type="submit" value="Nova vaga" class="btn btn-lg btn-orange">
    
                    </form>
                </div>
               
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>

{% endblock %}

companys/templates/companys.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}

{% block head %}
    <link rel="stylesheet" href="{% static 'company/css/company.css' %}">
{% endblock head %}

{% block content %}
    <div class="wrapper">
        <div class="box"> 
            <div class="header-box">
                {% if messages %}
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}
                <h2 class="titulo">Gerenciar empresas</h2>
                <a href="{% url 'new_company' %}" class="btn-nova-empresa">Nova empresa</a>
            </div>
            <div class="borda-box"></div>
            <div class="body-box">
            
                <form action="{% url 'show_companys' %}" method="GET">
                    {% csrf_token %}
                <div class="row">
                    
                        <div class="col-md-5">
                            <input type="text" placeholder="Busque pelo nome" class="form-control" name="name">
                        </div>

                        <div class="col-md-4">
                            <select class="form-select" name="technologies">
                                <option value="">Todas</option>
                                {% for tech in technologies%}
                                    <option value="{{tech.id}}">{{tech}}</option>
                                {% endfor %}
                            </select>
                        </div>
                    
                    <div class="col-md-3">
                        <input type="submit" value="FILTRAR" class="btn btn-lg btn-orange">
                    </div>
                </div>
                </form>

                <table class="tabela" cellpadding="20">
                    <tr>
                        <th>Nome</th>
                        <th>Endereço</th>
                        <th>Tecnologias usadas</th>
                        <th>Quantidade de vagas</th>
                        <th>Ação</th>
                    </tr>
                        {% for company in companys%}
                        <tr {% if not forloop.counter|is_even %} class="tabela-linha" {% endif %}>
                            <td>{{company.name}}</td>
                            <td>{{company.address}}</td>
                            <td>
                                <select class="form-select">                                    
                                    {% for tech in company.technology.all %}
                                        <option>{{tech}}</option>
                                    {% endfor %}                      
                                </select>
                            </td>
                            <td>
                                {% if company.number_job_vacancies > 0 %}
                                    <img src="{% static 'company/img/green-flag.svg' %}">
                                {% else %}
                                    <img src="{% static 'company/img/red-flag.svg' %}">
                                {% endif %}
                                    &nbsp&nbsp{{ company.number_job_vacancies }} vaga(s)
                            </td>
                            <td>
                                <a href="{% url 'company_details' company.id %}" class="btn-view"><img class="svg-icon" src="{% static 'company/img/eye.svg' %}" alt="Visualizar"></a>
                                <a href="{% url 'delete_company' company.id %}" class="btn-delete"><img class="svg-icon" src="{% static 'company/img/trash.svg' %}" alt="Deletar"></a>
                            </td>
                        </tr>
                    {% endfor %}
                    
                </table>
            </div>
        </div>
    </div>

{% endblock%}

companys/templates/new_company.html
{% extends "base.html" %}
{% load static %}

{% block head %}
    <link rel="stylesheet" href="{% static 'company/css/new_company.css' %}">
{% endblock head %}
{% block content %}

    <div class="wrapper">
        <div class="box">
            <div class="header">
                <h3 class="titulo">Nova empresa</h3>
            </div>

            <div class="body-box">
                {% if messages %}
                    {% for message in messages %}
                        <section class="alert {{message.tags}}">
                            {{message}}
                        </section>
                    {% endfor %}
                {% endif %}
                <form action="{% url 'new_company' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md">
                            <label>Nome:</label>
                            <input type="text" class="form-control" name="name" placeholder="Digite seu nome...">
                        </div>

                        <div class="col-md">
                            <label>E-mail:</label>
                            <input type="email" class="form-control" name="email" placeholder="email@gmail.com">
                        </div>

                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Cidade:</label>
                            <input type="text" class="form-control" name="city" placeholder="Digite a cidade da empresa...">
                        </div>

                        <div class="col-md">
                            <label>Endereço:</label>
                            <input type="text" class="form-control" name="address" placeholder="Rua...">
                        </div>

                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Nicho de mercado:</label>
                            <select class="form-control" name="category">
                                <option value="M">Marketing</option>
                                <option value="N">Nutrição</option>
                                <option value="D">Design</option>
                                <option value="T">Tecnologia</option>
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Tecnologias usadas:</label>
                            <select class="form-control" name="technologies" multiple>  
                                {% for tech in techs %}
                                    <option value="{{tech.id}}">{{tech.technology}}</option>
                                {% endfor %}                              
                                
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Característica da empresa:</label>
                            <textarea name="characteristics" class="form-control"></textarea>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md">
                            <label>Logo:</label>
                            <input type="file" class="form-control" name="logo">
                        </div>
                    </div>
                    <br>
                    <input type="submit" value="Nova empresa" class="btn btn-lg btn-orange">
                </form>
                
            </div>
        </div>
    </div>


{% endblock%}